commit_message: 🔄 Update via sync
replace:
  - before: project_name
    after: gh_fsync
files:
  - name: CONTRIBUTING.md
    source: https://github.com/Matt-Gleich/go_template/blob/master/CONTRIBUTING.md
    replace:
      - before: project_name
        after: gh_fsync2
  - name: LICENSE.md
    source: https://github.com/Matt-Gleich/go_template/blob/master/LICENSE.md
    replace:
      - before: author_name
        after: Matthew Gleich
