name: release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: make build-docker-platform
      - name: Push Image
        run: docker push mattgleich/gh_fsync:platform
